### ISSUE TITLE
Unable to turn off 

### ISSUE THREAD

**Issue by mhoskins83** [fjs21/homebridge-kumo#19]
When the thermostat is set in the off position the system is changed to Fan only in Kumo Cloud when it should be in the off state.

**Comment by fjs21** [comment]
Yes. That was intentional. However, it would be nice to have the plugin be able to completely switch off the unit. In the next version (1.4) I will restore the fan accessory. This way when the fan and heater/cooler are off the unit can switch off. If either is on, it will either heat/cool or be fan only.

**Comment by hansw1204** [comment]
Thank you, jjs21, I was wondering about that just now. Would be great to be able to turn on/off the fan separately.

**Comment by fjs21** [comment]
I'm pushing the update today. Would appreciate feedback in case it breaks anything.
