### ISSUE TITLE
Want to help with MSZ-FS series wall-mounted units

### ISSUE THREAD

**Issue by 1simonfish** [fjs21/homebridge-kumo#39]
I'd like to help add support for the MSZ-FS series units. They have a variety of features which aren't supported by the current plug-in which I'd like to be able to use.

**Comment by fjs21** [comment]
Feel free to submit a pull request. I'd be happy to incorporate. I would suggest you start by making a new "accessory" starting from either the 'ductless.ts' or 'ductless_simple.ts' files. You can then add the check for unitType (if it is reported by the device) in the platform.ts file so that your device is recognized and initialized.
