### ISSUE TITLE
Wrong IP Address being used for queryDevice_Direct

### ISSUE THREAD

**Issue by esetnik** [fjs21/homebridge-kumo#45]
[11/3/2021, 5:02:53 PM] [homebridge-kumo] queryDevice_Direct error: FetchError: request to http://192.168.1.205/api?m=24f1068d5ae939f69281368e4f9cb0320bc0e720e4a5ab9111a0ab6a292ae9d7 failed, reason: connect ECONNREFUSED 192.168.1.205:80

![IMG_D1E84FAED824-1](https://user-images.githubusercontent.com/664434/140131475-78d391fb-1b97-4db7-a03e-4ca307b933d4.jpeg)

The actual Kumo device is located at 192.168.1.200. I'm not sure where the plugin is getting the `205` address from.

**Comment by fjs21** [comment]
It must have changed from an original setting of 205. Are you by any chance using DHCP in your wifi router? 

I strongly recommend if you want to use direct access that the devices are kept on static IPs. If not, whenever the router decides to give out a different IP address you will get this error for a period of time. Unfortunately, I have not found out a way to override the Kumo derived IP address and it can take minutes/hours or longer to update. 

I had this problem once and moved to static IPs and its been good since. If you are unable to change to static IP addresses for your Kumo devices then I suggest unchecking the direct access button and just using the cloud based API.

**Comment by esetnik** [comment]
I already have the IP reservation (static IP) set to 200 for this device. And it has been connected to the 200 address for over a week. So is this a kumo cloud issue that they do not update their own cached IP address associated with the device?

**Comment by esetnik** [comment]
I moved the reservation to 205 and now it's working. Still seems like a bug in that it never updates the IP address if it changes.

**Comment by fjs21** [comment]
Yeah it's not ideal. The plugin gets the IP address reported from the Kumo cloud. So if the two are out of sync, you get the error. I could mask the error and just have the plugin revert to an indirect connection but this is also suboptimal as the user is expecting a 'direct' connection to be used if you check that box in the config. I think documentation is the better approach and making it clear that the direct connection should be used with static IPs.

**Comment by esetnik** [comment]
@fjs21 is there a log line which shows the directAccess IP being attempted?

**Comment by fjs21** [comment]
If you turn on debug in the homebridge UI. You should be able to tell. 

For now hold off as I think I found a bug in my new code that means that it won't wait until you get authenticated before proceeding. I need to add an "await".

**Comment by fjs21** [comment]
Ok. I have added additional logging so you can tell if directAccess (via local IP) was successful and additional log entries to demonstrate that a connection was successfully completed. These should appear shortly after homebridge is restarted.

**Comment by eleventhaus** [comment]
@esetnik just curious, what app that?

**Comment by esetnik** [comment]
> @esetnik just curious, what app that?

Eero iOS
