### ISSUE TITLE
API Failures and Homebrige performance impact 

### ISSUE THREAD

**Issue by FTI76** [fjs21/homebridge-kumo#52]
i’ve encountered errors with direct connection and via the api. 

i’ve put the Kumo plug-in on its own bridge and i’m not noticing any performance issues.  plug-in appears to be functional. 

![A9113B96-1E29-4C25-8084-6E568383771A](https://user-images.githubusercontent.com/73201651/146983001-6faf56db-121e-4912-ada5-e46d30c7bf1c.png)

**Comment by FTI76** [comment]
![0BDC645D-7F98-4F70-84BA-9C33F5343EA8](https://user-images.githubusercontent.com/73201651/146983480-19dfaa7d-4e99-4efa-8e20-17c3d735fb99.png)

**Comment by fjs21** [comment]
This is a little hard to diagnose. Do you get any errors when direct connect is off?

**Comment by FTI76** [comment]
> This is a little hard to diagnose. Do you get any errors when direct connect is off?

Hi. If you look there are two screenshots.  The first are the when direct connect is enabled.  The second is when it’s disabled.   From what I can tell it’s working alright in spite of these errors.  All my automations with the Mitsu devices are working.

**Comment by fjs21** [comment]
What type of device is homebridge running on? 

Not really sure what the first issue is as that's usually a username/password issue but it could mean something else too.

The second set of errors could be due to slow response from the API which might be due to slow/weak network connection which then causes a timeout in HomeKit. 

If you want to delve deeper, turn on debugging in the Homebridge UI and post the results - preferably as text rather than screenshots. Thanks

**Comment by FTI76** [comment]
HomeBridge is running on Libuntu VM with 4 CPUs and 3GB of Memory and Bridged Gigabit.  2.9xGB is generally free.  All three of the Mitsu Wifi Units show Full Connection strength to my Eero network and the credentials for Kumo Cloud are working alright.     Things seems to be working fine is spite of the errors so if you want to close this that's fine, or if you want me to collect any other debug logs I can do that also.   Overall I am very happy with this plugin, so thanks for your efforts.
